### ISSUE TITLE
Tablespace: Input validation is missing.

### ISSUE THREAD

**Issue by akshay-joshi** [akshay-joshi/TestRMToHub#396]
**This issue has been migrated from Redmine.**

Author Name: **Karen Blatchley** (@kblatchley)
Original Redmine Issue: [1110](https://redmine.postgresql.org/issues/1110)

Assignee: Murtuza Zabuawala

---
While creating the tablespace node, we are getting the error on the browser console.
Follow the below steps.

* Create the new tablespace. Give the name of the table space
* Go to "Variables" tab and press "Add" button. Do not enter the value.
* Click on the SQL tab.
* After above step, browser console will give error.

Same errors will be displayed when we do not enter the value for "Privileges" and "Security Labels" and click on SQL tab.

Created by Neel Patel 2016-03-11

[2016-03-11 Neel Patel] We are getting below error at python side when we do not add variable value.  Below error will come when we do not enter the security label and variables.

**Comment by akshay-joshi** [comment]
Author Name: **Karen Blatchley** (@kblatchley)


---
We are getting below error at python side when we do not add variable value.

Below error will come when we do not enter the security label and variables.
##########################
 res = adapt(value).getquoted()
psycopg2.ProgrammingError: can't adapt type 'Undefined'
##########################


Below error will come when we do not enter the Privileges.
##########################
 ValueError: Expecting value: line 1 column 1 (char 0)
2016-03-14 11:04:44,649: ERROR	pgadmin:	'grantee'
Traceback (most recent call last):
  File "/home/neel/Projects/pgAdmin4/new_pgadmin4/pgadmin4/web/pgadmin/browser/server_groups/servers/tablespaces/__init__.py", line 412, in msql
    SQL = self.get_sql(gid, sid, data, tsid)
  File "/home/neel/Projects/pgAdmin4/new_pgadmin4/pgadmin4/web/pgadmin/browser/server_groups/servers/tablespaces/__init__.py", line 467, in get_sql
    data['spcacl'] = parse_priv_to_db(data['spcacl'], 'TABLESPACE')
  File "/home/neel/Projects/pgAdmin4/new_pgadmin4/pgadmin4/web/pgadmin/browser/server_groups/servers/utils.py", line 85, in parse_priv_to_db
    'grantee': priv['grantee'],
KeyError: 'grantee'
##########################

**Comment by akshay-joshi** [comment]
Author Name: **Murtuza Zabuawala** (@mzabuawala)



---

-  status_id  was changed from    New   to  In Progress 
-  assigned_to_id  was configured    as 324

**Comment by akshay-joshi** [comment]
Author Name: **Murtuza Zabuawala** (@mzabuawala)


---
Variables & Privileges has been fixed already,

I have sent patch for Security label.

https://www.postgresql.org/message-id/CAKKotZRRLBBZSF%3DUeOzgO6QJ3CehT62PfZtqEY-MjP68nqbo_A%40mail.gmail.com

**Comment by akshay-joshi** [comment]
Author Name: **Anonymous** (Anonymous)


---
Applied in changeset 9ed2530b1f5da91a24235d2e60280df4d0bbda0b.

---

-  status_id  was changed from    In Progress   to  In Testing 
-  done_ratio  was changed from   0   to 90

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
This issue is resolved on Ubuntu 14.04 Linux 64

Commit ID:
----------
commit 97d49af43adc7b50a1d711fad445fab15bd48462

---

-  status_id  was changed from    In Testing   to  Resolved
