### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__context__': Issue on server delete 

### ISSUE THREAD

**Issue by akshay-joshi** [akshay-joshi/TestRMToHub#457]
**This issue has been migrated from Redmine.**

Author Name: **Karen Blatchley** (@kblatchley)
Original Redmine Issue: [1172](https://redmine.postgresql.org/issues/1172)

Assignee: Fahar Abbas

---
1. Delete any added server
 (right click on server -> click Delete/Drop)

Observation:
server get deleted,in JSON response it throws error

runTest (pgadmin.browser.server_groups.servers.tests.test_server_delete.ServersDeleteTestCase)
This function will get all available servers under object browser (Default Server Node url) ... 2016-05-13 14:23:54,443: ERROR pgadmin:	'NoneType' object has no attribute '__context__'
Traceback (most recent call last):
  File "/home/edb/Downloads/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 301, in delete
    info = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 
256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'

Created by Priyanka Shendge 2016-05-13

---

- [1172.png](https://redmine.postgresql.org/attachments/download/1058/1172.png) (priyanka shendge)

**Comment by akshay-joshi** [comment]
Author Name: **priyanka shendge** (priyanka shendge)



---

-  1058  was configured    as 1172.png 

---

- [1172.png](https://redmine.postgresql.org/attachments/download/1058/1172.png) (priyanka shendge)

**Comment by akshay-joshi** [comment]
Author Name: **Dave Page** (@dpage)


---
This can no longer be reproduced.

---

-  status_id  was changed from    New   to  In Testing

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
Tested Version:
Python 3.4

Commit ID:
----------
commit 790b28fb61df43aa8373b652b184bd14669b0abc

This issue is still reproducible with latest check in:

Here is the output in terminal:

2016-07-26 00:53:20,143: ERROR	pgadmin:	'NoneType' object has no attribute '__context__'
Traceback (most recent call last):
  File "/home/fahar/Projects/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 359, in delete
    info = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'



---

-  status_id  was changed from    In Testing   to  New

**Comment by akshay-joshi** [comment]
Author Name: **Murtuza Zabuawala** (@mzabuawala)


---
Can you verify if this is still the issue?

---

-  assigned_to_id  was configured    as 278

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
This is already resolved.

---

-  status_id  was changed from    New   to  Resolved
