### ISSUE TITLE
 "Error loading script- about/about"  message displayed with Desktop Runtime application on OS X

### ISSUE THREAD

**Issue by akshay-joshi** [akshay-joshi/TestRMToHub#601]
**This issue has been migrated from Redmine.**

Author Name: **Fahar Abbas** (@FaharAbbasRizvi)
Original Redmine Issue: [1329](https://redmine.postgresql.org/issues/1329)

Assignee: Ashesh Vashi

---
Tested Platform:

MAC 10.10

Installer location:

https://www.pgadmin.org/download/macosx4.php

There is only object option is available in pgAdmin4 and other options are not displayed and also error displayed "Error loading script- about/about".

Steps:
------
1. Download pgAdmin4 installer on MAC 10.10
2. Double click on pgadmin4-1.0-beta1.dmg file on /Users/fahar/Desktop
3. pgAdmin4 opened and there is only object option is available and error displayed "Error loading script- about/about"

---

- [Screen Shot 2016-06-10 at 9.42.21 am.png](https://redmine.postgresql.org/attachments/download/1256/Screen%20Shot%202016-06-10%20at%209.42.21%20am.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 3.58.29 pm.png](https://redmine.postgresql.org/attachments/download/1381/Screen%20Shot%202016-06-28%20at%203.58.29%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 4.51.58 pm.png](https://redmine.postgresql.org/attachments/download/1382/Screen%20Shot%202016-06-28%20at%204.51.58%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 4.54.41 pm.png](https://redmine.postgresql.org/attachments/download/1383/Screen%20Shot%202016-06-28%20at%204.54.41%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 12.30.50 pm.png](https://redmine.postgresql.org/attachments/download/1384/Screen%20Shot%202016-06-28%20at%2012.30.50%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-07-05 at 2.06.10 pm.png](https://redmine.postgresql.org/attachments/download/1423/Screen%20Shot%202016-07-05%20at%202.06.10%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-07-05 at 2.07.37 pm.png](https://redmine.postgresql.org/attachments/download/1424/Screen%20Shot%202016-07-05%20at%202.07.37%20pm.png) (Fahar Abbas)

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
It's a major issue and we can not resume testing on MAC 10.10 os x and changed the priority to high.

---

-  priority_id  was changed from    Normal   to  High

**Comment by akshay-joshi** [comment]
Author Name: **Dave Page** (@dpage)


---
I was able to reproduce this on an extremely slow OS X 10.9 VM. When executing the runtime from the console, I periodically saw issues like this:

2016-06-15 07:22:01,018: ERROR	pgadmin:	Exception on /dashboard/dashboard.js [GET]
Traceback (most recent call last):
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/__init__.py", line 245, in before_request
    login_user(user)
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask_security/utils.py", line 61, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/flask_login.py", line 681, in login_user
    session['_id'] = _create_identifier()
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/venv/lib/python/site-packages/werkzeug/local.py", line 341, in __setitem__
    self._get_current_object()[key] = value
  File "/Volumes/pgAdmin 4/pgAdmin 4.app/Contents/Resources/web/pgadmin/utils/session.py", line 87, in __setitem__
    conn.execute(self._set_sql, (key, sqlite3.Binary(value)))
OperationalError: database is locked

Different requests failed, but always with the database locked error.

**Comment by akshay-joshi** [comment]
Author Name: **Ashesh Vashi** (@asheshv)


---
This is not reproducible in general.

There is one configuration option 'SQLITE_TIMEOUT' in config.py regarding the sqlite locking issue.
SQLite locks the whole database, when accessing it, and does not allow to access other operation.

In order to resolve the issue of locking, we have introduced the 'SQLITE_TIMEOUT' configuration options for the same.
The user need to set it to higher value for it.

Dave,

Do you expect some other way to resolve this issue other than this configuration options?

---

-  assigned_to_id  was configured    as 6

**Comment by akshay-joshi** [comment]
Author Name: **Dave Page** (@dpage)


---
If it's a timeout issue, then that seems like a reasonable option.

---

-  assigned_to_id  was changed from   6   to 68

**Comment by akshay-joshi** [comment]
Author Name: **Ashesh Vashi** (@asheshv)


---
Should we document about this configuration option?
i.e.
- When you need to set this option.
- What value should be set?

---

-  assigned_to_id  was changed from   68   to 6

**Comment by akshay-joshi** [comment]
Author Name: **Dave Page** (@dpage)


---
Just include a suitable comment in the config file for now please.

---

-  assigned_to_id  was changed from   6   to 68

**Comment by akshay-joshi** [comment]
Author Name: **Anonymous** (Anonymous)


---
Applied in changeset f1eca516f08c644b5c4a7f0c1c88a70a43463928.

---

-  status_id  was changed from    New   to  In Testing 
-  done_ratio  was changed from   0   to 90

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
Tested Platform:
MAC 10.10

This issue is still reproducible on MAC 10.10

How I tested:
-------------

Scenario 1:
----------
Step:
-------
1. Download pgadmin4-1.0-beta2.dmg 
https://www.postgresql.org/ftp/pgadmin3/pgadmin4/v1.0-beta2/osx/
2. Copy this dmg file under /Users/fahar/Desktop
3. Double click on dmg file 
4. Accept the License agreement 
5. Launch pgAdmin4
6. Still "Error loading script- about/about"  message displayed




---

-  status_id  was changed from    In Testing   to  New

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
Scenario 2:
----------
Step:
-------
1. Download pgadmin4-1.0-beta2.dmg
https://www.postgresql.org/ftp/pgadmin3/pgadmin4/v1.0-beta2/osx/
2. Copy this dmg file under Application and drag pgAdmin under Application
3. Launch pgAdmin4
4. Error displayed and snapshot are attached for a reference.

---

-  1381  was configured    as Screen Shot 2016-06-28 at 3.58.29 pm.png 
-  1382  was configured    as Screen Shot 2016-06-28 at 4.51.58 pm.png 
-  1383  was configured    as Screen Shot 2016-06-28 at 4.54.41 pm.png 
-  1384  was configured    as Screen Shot 2016-06-28 at 12.30.50 pm.png 

---

- [Screen Shot 2016-06-28 at 3.58.29 pm.png](https://redmine.postgresql.org/attachments/download/1381/Screen%20Shot%202016-06-28%20at%203.58.29%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 4.51.58 pm.png](https://redmine.postgresql.org/attachments/download/1382/Screen%20Shot%202016-06-28%20at%204.51.58%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 4.54.41 pm.png](https://redmine.postgresql.org/attachments/download/1383/Screen%20Shot%202016-06-28%20at%204.54.41%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-06-28 at 12.30.50 pm.png](https://redmine.postgresql.org/attachments/download/1384/Screen%20Shot%202016-06-28%20at%2012.30.50%20pm.png) (Fahar Abbas)

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
Similar issue is reproducible if use python 3.3 with pgAdmin4

Tested Location:
----------------
https://builds.enterprisedb.com/builds/DailyBuilds/Installers/PG/Latest/9.6/UK/

Tested Platform:
MAC OS X 10.9

Steps.

1. Install PostgreSQL.zip installer
2. Launch pgAdmin4 
3. Add New server
4. Error displayed.

Please note in Release version of PostgreSQL-9.6-beta2 os x installer, pgAdmin4 is working fine with python 2.7 version. I am using fresh copy of MAC 10.9 VM.


---

-  1423  was configured    as Screen Shot 2016-07-05 at 2.06.10 pm.png 
-  1424  was configured    as Screen Shot 2016-07-05 at 2.07.37 pm.png 

---

- [Screen Shot 2016-07-05 at 2.06.10 pm.png](https://redmine.postgresql.org/attachments/download/1423/Screen%20Shot%202016-07-05%20at%202.06.10%20pm.png) (Fahar Abbas)
- [Screen Shot 2016-07-05 at 2.07.37 pm.png](https://redmine.postgresql.org/attachments/download/1424/Screen%20Shot%202016-07-05%20at%202.07.37%20pm.png) (Fahar Abbas)

**Comment by akshay-joshi** [comment]
Author Name: **Anonymous** (Anonymous)


---
Applied in changeset 61698b7b4db3eea39a034c7ff0f90d0c710ffcb8.

---

-  status_id  was changed from    New   to  In Testing

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)


---
This issue is resolved in Latest PostgreSQL-beta3 OS X installer.

Tested Python Version:
Python 2.7.11

Tested PostgreSQL version:
-----------------------
PostgreSQL 9.6 --- Built on 2016-07-19 05:42:34 IB: 15.10.1-201511121057


---

-  status_id  was changed from    In Testing   to  Resolved

**Comment by akshay-joshi** [comment]
Author Name: **Fahar Abbas** (@FaharAbbasRizvi)



---

-  done_ratio  was changed from   90   to 100
